#theme: jekyll-theme-minimal
title: Hello, world!
description: >-
  Descreption One Two Thre ...  # this means to ignore newlines until "baseurl:"

permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Merzak AOUDIA # add your name
author-img: merzak-aoudia.png # add your photo
about-author: I am a ... Always hungry to keep learning. # add description
social-github: amerzak # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# check it out later
# Disqus
# discus-identifier: mr-brown # add your discus identifier
# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
